### ISSUE TITLE
The English word "," does not have a definition. Please add it to the mini-dictionary.

### ISSUE THREAD

**Issue by szabgab** [LibreLingo/LibreLingo#1885]
```
Phrases:
  - Phrase: Pardon, ke ora es?
    Translation: "{Excuse me}, what time is it?"
```

Should Lili disregard any punctuations?

**Comment by kantord** [comment]
oh, that's interesting! 

at first look it seems like it might be because of the curly braces. I think the punctuation is being ignored in other cases :thinking:  so it must be a bug with the handling of curly braces in combination with the punctuation 

> Should Lili disregard any punctuations?

but this is only true in certain situation. in my opinion it's important to not disregard punctuation because for free form input they need to be validated

**Comment by RGBradley** [comment]
as an aside, it would be nice if errors could include the line number
I just spent a lot of time fixing: 
The English word "-" does not have a definition. Please add it to the mini-dictionary.
Turned out when I copied and pasted I had left out a key word, and my file had hundreds of  dashes that I had to go through one by one.

**Comment by szabgab** [comment]
@RGBradley could you provide a short example of it?
